### ISSUE TITLE
Context?

### ISSUE THREAD

**Issue by mathiasbynens** [GeoffreyBooth/browser-equivalence-edge-case#2]
What’s the context to this repo?

`import './foo'` treating the contents of `./foo` as a classic script instead of a module is a violation of the ECMAScript spec, i.e. a clear bug. Was this repo used as part of a bug report against Node.js?

**Comment by GeoffreyBooth** [comment]
The context? Beyond what’s explained in the README?

This repo was created to demonstrate an issue that was under discussion in https://github.com/nodejs/modules/issues/142. You were part of that discussion, and indeed you also submitted a PR against this repo! 😄
